# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'HiFive' do
    pod 'AFNetworking', '~> 2.6'
    pod "youtube-ios-player-helper", "~> 0.1.4"
    pod 'Alamofire', '~> 4.0'
end

target 'HiFiveUITests' do

end

